name = "spranki-art"
compatibility_date = "2024-12-27"
pages_build_output_dir = "."

[env.production]
name = "spranki-art"
compatibility_date = "2024-12-27"
account_id = "YOUR_ACCOUNT_ID"
compatibility_flags = ["nodejs_compat"]

# 环境变量配置
[env.production.vars]
ENVIRONMENT = "production"
DEBUG = "false" 